/**
 * pcreative-license.js — license client for Shopify themes (anti-nulled).
 *
 * Auto-generated by ThemeForge. Reads the merchant's purchase code from
 * theme settings, exchanges it for a signed JWT against the licensing
 * backend, verifies the JWT offline with the embedded RS256 public key,
 * and exposes window.pcreativeLicense.{isValid, claims, gate} so the
 * theme can hide premium sections and watermark unlicensed installs.
 *
 * Backend URL and public key are placeholders — replace via the
 * scaffolder's licensing_config.load() or your own build step. The
 * backend must implement the pcreative protocol:
 *   POST  __LICENSE_API_URL__   body: { license_key, product, domain }
 *         response: { valid: true, jwt: "<RS256>" }
 *
 * The JWT must carry: sub, product, domain, type, watermark, exp, iss.
 *
 * Hosted as static asset → cargada con <script defer src="{{ 'pcreative-license.js' | asset_url }}"></script>
 */
(function () {
  "use strict";

  var PUBKEY_PEM = "__LICENSE_PUBKEY__";
  var EXPECTED_ISSUER = "__LICENSE_ISSUER__";
  var EXPECTED_PRODUCT = "__SLUG__";
  var LICENSE_API_URL = "__LICENSE_API_URL__";
  var STORAGE_KEY = "pcreative.license.__SLUG__";
  var HEARTBEAT_MS = 24 * 60 * 60 * 1000; // 24h

  var ns = window.pcreativeLicense = window.pcreativeLicense || {};
  ns.state = { ready: false, valid: false, claims: null, error: null };

  // ── helpers ────────────────────────────────────────────────────────
  function b64UrlToBytes(s) {
    s = s.replace(/-/g, "+").replace(/_/g, "/");
    while (s.length % 4) s += "=";
    var raw = atob(s);
    var bytes = new Uint8Array(raw.length);
    for (var i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
    return bytes;
  }
  function b64UrlToString(s) {
    return new TextDecoder().decode(b64UrlToBytes(s));
  }
  function pemToBinary(pem) {
    var clean = pem
      .replace(/-----BEGIN PUBLIC KEY-----/g, "")
      .replace(/-----END PUBLIC KEY-----/g, "")
      .replace(/\s+/g, "");
    return Uint8Array.from(atob(clean), function (c) { return c.charCodeAt(0); }).buffer;
  }

  async function importKey() {
    return crypto.subtle.importKey(
      "spki",
      pemToBinary(PUBKEY_PEM),
      { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
      false,
      ["verify"]
    );
  }

  async function verifyJWT(token) {
    var parts = token.split(".");
    if (parts.length !== 3) throw new Error("malformed jwt");
    var header = JSON.parse(b64UrlToString(parts[0]));
    if (header.alg !== "RS256") throw new Error("alg " + header.alg + " not allowed");
    var key = await importKey();
    var sig = b64UrlToBytes(parts[2]);
    var data = new TextEncoder().encode(parts[0] + "." + parts[1]);
    var ok = await crypto.subtle.verify("RSASSA-PKCS1-v1_5", key, sig, data);
    if (!ok) throw new Error("signature invalid");
    var claims = JSON.parse(b64UrlToString(parts[1]));
    if (claims.iss !== EXPECTED_ISSUER) throw new Error("issuer mismatch");
    if (claims.product !== EXPECTED_PRODUCT) throw new Error("product mismatch");
    if (claims.exp && Date.now() >= claims.exp * 1000) throw new Error("expired");
    return claims;
  }

  // ── storage ────────────────────────────────────────────────────────
  function load() {
    try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; }
    catch (e) { return {}; }
  }
  function save(d) {
    try { localStorage.setItem(STORAGE_KEY, JSON.stringify(d)); } catch (e) {}
  }

  // ── activate / heartbeat ───────────────────────────────────────────
  async function activate(licenseKey, domain) {
    var r = await fetch(LICENSE_API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        license_key: licenseKey,
        product: EXPECTED_PRODUCT,
        domain: domain,
      }),
    });
    if (!r.ok) throw new Error("activate http " + r.status);
    var json = await r.json();
    if (!json.valid || !json.jwt) throw new Error("activate response invalid");
    return json.jwt;
  }

  // ── public API ─────────────────────────────────────────────────────
  ns.isValid = function () { return ns.state.valid; };
  ns.claims = function () { return ns.state.claims; };
  /** Marca sections gateadas: oculta data-pcreative-gated si no hay licencia. */
  ns.gate = function () {
    if (ns.state.valid) return;
    var els = document.querySelectorAll("[data-pcreative-gated='true']");
    for (var i = 0; i < els.length; i++) {
      els[i].setAttribute("hidden", "true");
      els[i].style.display = "none";
    }
  };

  // ── boot ───────────────────────────────────────────────────────────
  async function boot() {
    var settings = (window.theme && window.theme.licenseSettings) || {};
    var domain = (window.Shopify && window.Shopify.shop) || location.host;
    var cached = load();

    // 1) intenta JWT cacheado.
    if (cached.jwt) {
      try {
        var claims = await verifyJWT(cached.jwt);
        if (claims.domain === domain) {
          ns.state = { ready: true, valid: true, claims: claims, error: null };
          // heartbeat si toca
          if (!cached.lastHeartbeat || (Date.now() - cached.lastHeartbeat) > HEARTBEAT_MS) {
            try {
              var fresh = await activate(settings.purchaseCode || cached.licenseKey, domain);
              save({ jwt: fresh, licenseKey: settings.purchaseCode || cached.licenseKey, lastHeartbeat: Date.now() });
            } catch (e) { /* mantenemos el cache, intentamos próxima carga */ }
          }
          ns.gate();
          return;
        }
      } catch (e) { /* cache inválido — re-activamos */ }
    }

    // 2) sin cache → activa con el purchase code de settings.
    if (!settings.purchaseCode) {
      ns.state = { ready: true, valid: false, claims: null, error: "no license code" };
      ns.gate();
      return;
    }
    try {
      var jwt = await activate(settings.purchaseCode, domain);
      var claims2 = await verifyJWT(jwt);
      save({ jwt: jwt, licenseKey: settings.purchaseCode, lastHeartbeat: Date.now() });
      ns.state = { ready: true, valid: true, claims: claims2, error: null };
    } catch (e) {
      ns.state = { ready: true, valid: false, claims: null, error: String(e) };
    }
    ns.gate();
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", boot);
  else boot();
})();
